name: CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements/base.txt
            requirements/dev.txt

      - name: Setup
        shell: bash
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install -U pip
          pip install -r requirements/base.txt -r requirements/dev.txt
          # Ensure scripts are executable (defensive)
          chmod +x scripts/*.sh 2>/dev/null || true

      - name: Run repo checks (push = full, PR = fast)
        shell: bash
        run: |
          . .venv/bin/activate
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ./scripts/format.sh --check --changed
            ./scripts/lint.sh --changed
          else
            ./scripts/format.sh --check
            ./scripts/lint.sh
          fi
          ./scripts/test.sh || true  # harmless if no tests yet
